const KEY='gym_tycoon_v4';
const PREVKEY='gym_tycoon_v3';
const OLDKEY='gym_tycoon_v1';
const machines=[
 ['treadmill','跑步機','🏃',1200,3,'cardio'],['bench','臥推架','🏋️',1800,5,'strength'],['squat','深蹲架','🦵',2400,7,'strength'],['bike','飛輪車','🚴',3200,9,'cardio'],['cable','滑輪機','💪',4500,12,'strength'],['sauna','三溫暖','🧖',8000,20,'cardio']
];
const staffs=[['coach','健身教練','🧑‍🏫',3000,'收入 +15%，降低排隊不滿'],['desk','櫃檯人員','🙋',1800,'新會員成長 +20%'],['clean','清潔人員','🧹',1500,'評價更容易提升'],['manager','店長','🧑‍💼',7000,'所有收入再 +10%']];
const quests=[
 {id:'q1',name:'第一桶金',desc:'累積營收達 $10,000',reward:1500,ok:g=>g.totalRevenue>=10000},
 {id:'q2',name:'器材控',desc:'持有 6 台器材',reward:2000,ok:g=>totalMachines()>=6},
 {id:'q3',name:'人氣健身房',desc:'會員達 50 人',reward:3000,ok:g=>g.members>=50},
 {id:'q4',name:'五星之路',desc:'評價達 4.5',reward:4000,ok:g=>g.rating>=4.5},
 {id:'q5',name:'旗艦店',desc:'健身房升到 Lv.4',reward:6000,ok:g=>g.level>=4}
];
function fresh(){return{money:5000,members:8,rating:3.5,prestige:0,day:1,hour:8,todayIncome:0,totalRevenue:0,served:0,bestDay:0,level:1,fee:800,machines:{treadmill:1},staff:{},claimed:{},machineLv:{},classes:{},branches:1,layout:{},vipMembers:[],coachXP:0,events:['🎉 健身房正式開幕！會員已經在門口排隊了。']}}
function load(){try{let v=JSON.parse(localStorage.getItem(KEY));if(v)return {...fresh(),...v};let prev=JSON.parse(localStorage.getItem(PREVKEY));if(prev)return {...fresh(),...prev,machineLv:prev.machineLv||{},classes:prev.classes||{},branches:prev.branches||1,layout:prev.layout||{},vipMembers:prev.vipMembers||[],coachXP:prev.coachXP||0};let old=JSON.parse(localStorage.getItem(OLDKEY));if(old)return {...fresh(),...old,totalRevenue:old.totalRevenue||0,served:0,bestDay:0,fee:800,prestige:0,claimed:{}}}catch(e){}return fresh()}
let g=load(),animating=false;
const $=id=>document.getElementById(id); const fmt=n=>'$'+Math.floor(n).toLocaleString();
function totalMachines(){return Object.values(g.machines).reduce((a,b)=>a+b,0)}
function capacity(){return 10+totalMachines()*4+(g.level-1)*20}
function demand(){let base=Math.max(3,Math.round(g.members*(0.15+Math.random()*0.12)));let pricePenalty=Math.max(.55,1-(g.fee-800)/1800);return Math.max(1,Math.round(base*pricePenalty))}
function revenuePerVisitor(){let eq=machines.reduce((s,m)=>s+(g.machines[m[0]]||0)*m[4]*(1+((g.machineLv||{})[m[0]]||0)*.12),0);let mult=(g.staff.coach?1.15:1)*(g.staff.manager?1.10:1);return Math.round((13+eq*0.7+g.fee/55)*mult)}
function hourly(){return Math.round(Math.min(g.members,capacity())*.22*revenuePerVisitor())}
function save(){localStorage.setItem(KEY,JSON.stringify(g));render()}
function push(s){g.events.unshift(s);g.events=g.events.slice(0,7)}
function toastMsg(s){let t=$('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
function tab(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');render()}
function setFee(v){g.fee=+v;save()}
function machineSlots(){let out=[];let cardio=[[39,17],[52,17],[65,17],[78,17],[39,31],[52,31],[65,31],[78,31]];let strength=[[39,59],[52,59],[65,59],[78,59],[39,75],[52,75],[65,75],[78,75]];let ci=0,si=0;machines.forEach(m=>{for(let i=0;i<(g.machines[m[0]]||0);i++){let arr=m[5]==='cardio'?cardio:strength;let idx=m[5]==='cardio'?ci++:si++;let p=arr[idx%arr.length];out.push({id:m[0],name:m[1],icon:m[2],x:p[0]+Math.floor(idx/arr.length)*4,y:p[1]})}});return out}
function renderScene(){let scene=$('gymScene');scene.querySelectorAll('.equip,.memberDot').forEach(n=>n.remove());machineSlots().forEach((m,i)=>{let key=m.id+'_'+i,pos=(g.layout||{})[key],d=document.createElement('div');d.className='equip';d.style.left=(pos?.x??m.x)+'%';d.style.top=(pos?.y??m.y)+'%';d.innerHTML=`${m.icon}<small>${m.name}</small>`;let drag=false;const mv=e=>{if(!drag)return;e.preventDefault();let r=scene.getBoundingClientRect(),p=e.touches?e.touches[0]:e,x=Math.max(1,Math.min(90,(p.clientX-r.left)/r.width*100)),y=Math.max(5,Math.min(84,(p.clientY-r.top)/r.height*100));d.style.left=x+'%';d.style.top=y+'%';g.layout[key]={x,y}};const up=()=>{if(!drag)return;drag=false;document.removeEventListener('mousemove',mv);document.removeEventListener('mouseup',up);document.removeEventListener('touchmove',mv);document.removeEventListener('touchend',up);localStorage.setItem(KEY,JSON.stringify(g));toastMsg('器材位置已儲存')};d.addEventListener('mousedown',e=>{e.preventDefault();drag=true;document.addEventListener('mousemove',mv);document.addEventListener('mouseup',up)});d.addEventListener('touchstart',()=>{drag=true;document.addEventListener('touchmove',mv,{passive:false});document.addEventListener('touchend',up)},{passive:true});scene.appendChild(d)})}
function animateHour(visitors,servedCount,queueCount,earned){animating=true;$('operateBtn').disabled=true;renderScene();let scene=$('gymScene'),slots=machineSlots();let people=Math.min(visitors,8);$('visitors').textContent=people;$('queue').textContent=queueCount;for(let i=0;i<people;i++){let p=document.createElement('div');p.className='memberDot';p.textContent=['🙂','😎','🤓','😁','🧢','👩','🧔','👱'][i%8];p.style.left='6%';p.style.top=(70+i%4*6)+'%';scene.appendChild(p);setTimeout(()=>{let slot=slots[i%Math.max(1,slots.length)]||{x:48,y:48};p.style.left=(slot.x+2)+'%';p.style.top=(slot.y+4)+'%';p.classList.add('busy');if(i>=servedCount){let b=document.createElement('span');b.className='bubble';b.textContent='排隊中…';p.appendChild(b)}},150+i*80);setTimeout(()=>{p.style.left='9%';p.style.top='82%';p.classList.remove('busy')},1050+i*55);setTimeout(()=>p.remove(),1750+i*55)}setTimeout(()=>{animating=false;$('operateBtn').disabled=false;$('visitors').textContent='0';$('queue').textContent='0';toastMsg(`本小時營收 +${fmt(earned)}`)},1950)}
function nextHour(){if(animating)return;let visitors=Math.min(demand(),capacity()),machineCap=Math.max(1,totalMachines()*2),servedCount=Math.min(visitors,machineCap),queueCount=Math.max(0,visitors-machineCap);let earn=Math.round(servedCount*revenuePerVisitor()*(queueCount>0?.94:1));g.money+=earn;g.todayIncome+=earn;g.totalRevenue+=earn;g.served+=servedCount;g.hour++;if(g.staff.coach)g.coachXP+=servedCount;if(Math.random()<.10&&g.vipMembers.length<12){let names=['阿哲','小美','Ken','Yuki','阿凱','Mina','Leo','小安','Rina','大雄'],goals=['增肌','減脂','體能','塑形'],n=names[Math.floor(Math.random()*names.length)];if(!g.vipMembers.some(v=>v.name===n)){g.vipMembers.push({name:n,goal:goals[Math.floor(Math.random()*goals.length)],lv:1,progress:0});push(`🌟 ${n} 成為常客會員！`)}}g.vipMembers.forEach(v=>{v.progress+=Math.max(2,Math.round(servedCount/2));if(v.progress>=100){v.progress-=100;v.lv++;g.prestige+=2;push(`💪 ${v.name} 升到 Lv.${v.lv}`)}});
 if(queueCount>=4){g.rating=Math.max(1,g.rating-(g.staff.coach?.015:.035));push(`😓 尖峰時段有 ${queueCount} 人排隊，評價受到影響。`)}else if(Math.random()<.28){g.rating=Math.min(5,g.rating+(g.staff.clean?.05:.02));push('⭐ 會員對今天的訓練體驗很滿意！')}
 let growthChance=.25*(g.staff.desk?1.2:1)*Math.max(.35,1-(g.fee-800)/1400);if(Math.random()<growthChance){let grow=Math.max(1,Math.round((g.rating-2)*2));g.members+=grow;push(`👥 口碑帶來 ${grow} 位新會員！`)}
 if(Math.random()<.10){let d=Math.floor(120+Math.random()*260);g.money=Math.max(0,g.money-d);push(`🔧 器材臨時維護支出 ${fmt(d)}`)}
 if(g.hour>=22){g.bestDay=Math.max(g.bestDay,g.todayIncome);let bonus=Math.round(g.todayIncome*.05);g.money+=bonus;g.prestige+=Math.max(1,Math.round(g.rating));push(`🌙 第 ${g.day} 天結束：營收 ${fmt(g.todayIncome)}，營運獎勵 ${fmt(bonus)}`);g.day++;g.hour=8;g.todayIncome=0}
 save();animateHour(visitors,servedCount,queueCount,earn)}
function buyMachine(id){let m=machines.find(x=>x[0]===id),count=g.machines[id]||0,cost=Math.round(m[3]*(1+count*.35));if(g.money<cost)return toastMsg('資金不足');g.money-=cost;g.machines[id]=count+1;g.rating=Math.min(5,g.rating+.04);push(`🏋️ 新增 ${m[1]}，場館容量提升。`);save();toastMsg(`${m[1]} 已進場`) }
function hire(id){let s=staffs.find(x=>x[0]===id);if(g.staff[id])return;if(g.money<s[3])return toastMsg('資金不足');g.money-=s[3];g.staff[id]=1;push(`🤝 ${s[1]} 加入團隊`);save()}
function upgradeMachine(id){let m=machines.find(x=>x[0]===id),lv=(g.machineLv[id]||0),cost=Math.round(m[3]*(lv+1)*1.25);if(!(g.machines[id]>0))return toastMsg('請先購買器材');if(g.money<cost)return toastMsg('資金不足');g.money-=cost;g.machineLv[id]=lv+1;g.prestige+=2;push(`✨ ${m[1]} 升級到 Lv.${lv+2}`);save()}
function startClass(type){let data={yoga:['瑜珈課','🧘',1200,6],spin:['飛輪課','🚴',1800,9],pt:['私人教練課','💪',2500,12]}[type];if(!g.staff.coach)return toastMsg('需要先聘請健身教練');if(g.money<data[2])return toastMsg('資金不足');g.money-=data[2];let gain=Math.round(data[3]*(1+g.rating/5));g.members+=Math.ceil(gain/3);g.rating=Math.min(5,g.rating+.06);g.prestige+=2;let earn=gain*Math.round(g.fee/20);g.money+=earn;g.totalRevenue+=earn;push(`${data[1]} ${data[0]}爆滿！帶來 ${fmt(earn)} 收入`);save();toastMsg(`${data[0]} 開課成功`)}
function openBranch(){let cost=50000*g.branches;if(g.level<4)return toastMsg('主館需達 Lv.4');if(g.money<cost)return toastMsg('資金不足');g.money-=cost;g.branches++;g.prestige+=25;g.members+=25;push(`🏙️ 第 ${g.branches} 間分店正式開幕！`);save();toastMsg('新分店開幕！')}
function upgrade(){let cost=g.level*10000;if(g.money<cost)return toastMsg('資金不足');g.money-=cost;g.level++;g.rating=Math.min(5,g.rating+.18);g.prestige+=10;push(`🚀 擴建完成！健身房升級到 Lv.${g.level}`);save();toastMsg('擴建完成！')}
function claim(id){let q=quests.find(x=>x.id===id);if(!q||g.claimed[id]||!q.ok(g))return;g.claimed[id]=1;g.money+=q.reward;g.prestige+=5;push(`🎁 完成任務「${q.name}」，獲得 ${fmt(q.reward)}`);save();toastMsg('任務獎勵已領取')}
function resetGame(){if(confirm('確定重新開始？目前進度會清除。')){g=fresh();localStorage.removeItem(OLDKEY);save()}}
function render(){ $('money').textContent=fmt(g.money);$('members').textContent=g.members;$('rating').textContent=g.rating.toFixed(1);$('prestige').textContent=g.prestige;$('day').textContent=g.day;$('clock').textContent=String(g.hour).padStart(2,'0')+':00';$('daybar').style.width=((g.hour-8)/14*100)+'%';$('incomeText').textContent=`今日收入 ${fmt(g.todayIncome)}`;$('hourlyText').textContent=fmt(hourly());$('levelText').textContent=`${g.level<3?'街角小型健身房':g.level<5?'人氣健身中心':'城市旗艦健身房'} · Lv.${g.level}`;$('sceneStatus').textContent=`容量 ${capacity()} 人 · ${totalMachines()} 台設備 · 月費 ${fmt(g.fee)}`;
 $('events').innerHTML=g.events.map(x=>`<div class="card event">${x}</div>`).join('');
 $('machineList').innerHTML=machines.map(m=>{let c=g.machines[m[0]]||0,cost=Math.round(m[3]*(1+c*.35));return `<div class="card machine"><span class="badge">持有 ${c}</span><div class="ico">${m[2]}</div><h3>${m[1]}</h3><p>減少排隊並提升每位會員的消費能力。</p><button class="buy" onclick="buyMachine('${m[0]}')">購買 ${fmt(cost)}</button><button class="secondary" style="width:100%;margin-top:6px" onclick="upgradeMachine('${m[0]}')">升級 Lv.${(g.machineLv[m[0]]||0)+1} → ${(g.machineLv[m[0]]||0)+2}</button></div>`}).join('');
 $('staffList').innerHTML=staffs.map(s=>`<div class="card machine"><span class="badge">${g.staff[s[0]]?'已聘用':'未聘用'}</span><div class="ico">${s[2]}</div><h3>${s[1]}</h3><p>${s[4]}</p><button class="buy" ${g.staff[s[0]]?'disabled':''} onclick="hire('${s[0]}')">${g.staff[s[0]]?'已聘用':'聘用 '+fmt(s[3])}</button></div>`).join('');
 let cost=g.level*10000;$('upgradeList').innerHTML=`<div class="card"><h3>🏢 擴建 Lv.${g.level} → Lv.${g.level+1}</h3><p class="muted">增加 20 人容量、提高評價並獲得 10 聲望。</p><button class="buy" onclick="upgrade()">擴建 ${fmt(cost)}</button></div><div class="card" style="margin-top:10px"><h3>🏙️ 連鎖分店</h3><p class="muted">目前 ${g.branches} 間店。主館 Lv.4 後可開新分店，每間分店增加會員與聲望。</p><button class="buy" onclick="openBranch()">開設第 ${g.branches+1} 間店 ${fmt(50000*g.branches)}</button></div>`;
 $('feeSlider').value=g.fee;$('feeText').textContent=fmt(g.fee);
 $('questList').innerHTML=quests.map(q=>{let done=q.ok(g),claimed=g.claimed[q.id];return `<div class="card quest ${done?'done':''}"><div><h4>${done?'✅':'🎯'} ${q.name}</h4><div class="muted">${q.desc}</div><div class="reward">獎勵 ${fmt(q.reward)}</div></div><button class="secondary" ${!done||claimed?'disabled':''} onclick="claim('${q.id}')">${claimed?'已領取':done?'領取':'進行中'}</button></div>`}).join('');
 $('totalRevenue').textContent=fmt(g.totalRevenue);$('served').textContent=g.served.toLocaleString();$('bestDay').textContent=fmt(g.bestDay);if($('memberRoster')){$('coachLv').textContent='Lv.'+(1+Math.floor(g.coachXP/120));$('coachXp').style.width=(g.coachXP%120)/120*100+'%';$('memberRoster').innerHTML=g.vipMembers.length?g.vipMembers.map(v=>`<div class="card vip"><div class="avatar">${v.goal==='增肌'?'🏋️':v.goal==='減脂'?'🏃':'🙂'}</div><div><b>${v.name} · Lv.${v.lv}</b><div class="muted">目標：${v.goal}</div><div class="progress memberProg"><i style="width:${v.progress}%"></i></div></div></div>`).join(''):'<div class="card muted">繼續營業，常客會員會逐漸出現。</div>'}renderScene()}
render();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
